export const APPLE_PODCAST_CATEGORIES = [
  {
    category: "Arts",
    subcategories: [
      "",
      "Books",
      "Design",
      "Fashion & Beauty",
      "Food",
      "Performing Arts",
      "Visual Arts",
    ],
  },
  {
    category: "Business",
    subcategories: [
      "",
      "Careers",
      "Entrepreneurship",
      "Investing",
      "Management",
      "Marketing",
      "Non-Profit",
    ],
  },
  {
    category: "Comedy",
    subcategories: ["", "Comedy Interviews", "Improv", "Stand-Up"],
  },
  {
    category: "Education",
    subcategories: [
      "",
      "Courses",
      "How To",
      "Language Learning",
      "Self-Improvement",
    ],
  },
  {
    category: "Fiction",
    subcategories: ["", "Comedy Fiction", "Drama", "Science Fiction"],
  },
  {
    category: "Government",
    subcategories: [],
  },
  {
    category: "History",
    subcategories: [],
  },
  {
    category: "Health & Fitness",
    subcategories: [
      "",
      "Alternative Health",
      "Fitness",
      "Medicine",
      "Mental Health",
      "Nutrition",
      "Sexuality",
    ],
  },
  {
    category: "Kids & Family",
    subcategories: [
      "",
      "Education for Kids",
      "Parenting",
      "Pets & Animals",
      "Stories for Kids",
    ],
  },
  {
    category: "Leisure",
    subcategories: [
      "",
      "Animation & Manga",
      "Automotive",
      "Aviation",
      "Crafts",
      "Games",
      "Hobbies",
      "Home & Garden",
      "Video Games",
    ],
  },
  {
    category: "Music",
    subcategories: [
      "",
      "Music Commentary",
      "Music History",
      "Music Interviews",
    ],
  },
  {
    category: "News",
    subcategories: [
      "",
      "Business News",
      "Daily News",
      "Entertainment News",
      "News Commentary",
      "Politics",
      "Sports News",
      "Tech News",
    ],
  },
  {
    category: "Religion & Spirituality",
    subcategories: [
      "",
      "Buddhism",
      "Christianity",
      "Hinduism",
      "Islam",
      "Judaism",
      "Religion",
      "Spirituality",
    ],
  },
  {
    category: "Science",
    subcategories: [
      "",
      "Astronomy",
      "Chemistry",
      "Earth Sciences",
      "Life Sciences",
      "Mathematics",
      "Natural Sciences",
      "Nature",
      "Physics",
      "Social Sciences",
    ],
  },
  {
    category: "Society & Culture",
    subcategories: [
      "",
      "Documentary",
      "Personal Journals",
      "Philosophy",
      "Places & Travel",
      "Relationships",
    ],
  },
  {
    category: "Sports",
    subcategories: [
      "",
      "Baseball",
      "Basketball",
      "Cricket",
      "Fantasy Sports",
      "Football",
      "Golf",
      "Hockey",
      "Rugby",
      "Running",
      "Soccer",
      "Swimming",
      "Tennis",
      "Volleyball",
      "Wilderness",
      "Wrestling",
    ],
  },
  {
    category: "Technology",
    subcategories: [],
  },
  {
    category: "True Crime",
    subcategories: [],
  },
  {
    category: "TV & Film",
    subcategories: [
      "",
      "After Shows",
      "Film History",
      "Film Interviews",
      "Film Reviews",
      "TV Reviews",
    ],
  },
];
