#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm test
npm run typecheck
npm run lint
npm run prettier
cargo fmt --manifest-path=packages/app/src-tauri/Cargo.toml --all -- --check
cargo test --manifest-path=packages/app/src-tauri/Cargo.toml 
