name: "test-on-pr"
on: [pull_request]

jobs:
  test-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, macos-13, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libasound2-dev

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: 'packages/app/src-tauri -> target'
          cache-directories: "packages/app/src-tauri/binaries"

      - name: install frontend dependencies
        run: npm install

      - name: build ui
        run: npm run build:ui

      - name: run typescript tests
        run: npm run test

      - name: rustc details
        run: rustc -vV

      - name: run rust tests
        run: cargo test
        working-directory: packages/app/src-tauri
        
      - name: run rust build
        run: cargo build
        working-directory: packages/app/src-tauri